// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class 0AmountCashTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 0AmountCash() {
    driver.get("https://ncjwavic--dev.lightning.force.com/lightning/n/Bulk_Donations");
    driver.findElement(By.xpath("//td[2]/div/div/div[2]/div/input")).click();
    driver.findElement(By.xpath("//td[2]/div/div/div[2]/div/input")).sendKeys("mr selen");
    driver.findElement(By.cssSelector(".slds-lookup__list:nth-child(2) .slds-media")).click();
    driver.findElement(By.xpath("//td[3]/div/div/div[2]/div/input")).click();
    driver.findElement(By.xpath("//td[3]/div/div/div[4]/ul/li/span/div/span")).click();
    driver.findElement(By.xpath("//lightning-input/div/input")).click();
    driver.findElement(By.xpath("//lightning-input/div/input")).sendKeys("0");
    driver.findElement(By.xpath("//td[6]/div/div/div/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[6]/div/div/div/select"));
      dropdown.findElement(By.cssSelector("*:nth-child(1)")).click();
    }
    driver.findElement(By.xpath("//button[contains(.,\'Save\')]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".slds-theme--error")));
    }
  }
}
