var webdriver = require('selenium-webdriver');
var chrome = require('selenium-webdriver/chrome');
var path = require('chromedriver').path;

var service = new chrome.ServiceBuilder(path).build();
chrome.setDefaultService(service);

var driver = new webdriver.Builder()
    .withCapabilities(webdriver.Capabilities.chrome())
    .build();


 // Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Cash', function() {
  this.timeout(70000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Cash', async function() {
    await driver.get("https://ncjwavic--dev.lightning.force.com/lightning/n/Bulk_Donations")
    await driver.sleep(7000)
    await driver.findElement(By.xpath("//td[2]/div/div/div[2]/div/input")).click()
    await driver.findElement(By.xpath("//td[2]/div/div/div[2]/div/input")).sendKeys("mr selen")
    await driver.findElement(By.xpath("//div[4]/ul/li/span")).click()
    await driver.findElement(By.xpath("//td[3]/div/div/div[2]/div/input")).click()
    await driver.findElement(By.xpath("//td[3]/div/div/div[4]/ul/li/span/div/span")).click()
    await driver.findElement(By.xpath("//lightning-input/div/input")).sendKeys("20")
    {
      const dropdown = await driver.findElement(By.xpath("//td[6]/div/div/div/select"))
      await dropdown.findElement(By.css("*[value='Cash']")).click()
    }
    await driver.findElement(By.xpath("//button[contains(.,\'Save\')]")).click()
    await driver.wait(until.elementLocated(By.css(".slds-theme--success")), 20000)
  })
})
